name: Tests

on:
  push:
    branches: [ '*' ]  # Run on any pushed branch
  pull_request:
    branches: [ develop, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 27.1
          - 28.2
          - 29.1
          - snapshot

    steps:
    - uses: actions/checkout@v3

    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - name: Check syntax
      run: |
        emacs -Q --batch \
          --eval "(add-to-list 'load-path \"$GITHUB_WORKSPACE\")" \
          --eval "(find-file \"$GITHUB_WORKSPACE/org-super-links.el\")" \
          --eval "(message \"Checking org-super-links.el...\")" \
          --eval "(condition-case err (check-parens) (error (message \"Syntax error in org-super-links.el: %S\" err) (kill-emacs 1)))" \
          --eval "(find-file \"$GITHUB_WORKSPACE/org-super-links-tests.el\")" \
          --eval "(message \"Checking org-super-links-tests.el...\")" \
          --eval "(condition-case err (check-parens) (error (message \"Syntax error in org-super-links-tests.el: %S\" err) (kill-emacs 1)))"

    - name: Run tests
      run: |
        emacs -Q --batch \
          --eval "(add-to-list 'load-path \"$GITHUB_WORKSPACE\")" \
          --eval "(condition-case err (require 'org) (error (message \"Error loading org: %S\" err) (kill-emacs 1)))" \
          --eval "(condition-case err (require 'ert) (error (message \"Error loading ert: %S\" err) (kill-emacs 1)))" \
          --eval "(condition-case err (require 'org-super-links) (error (message \"Error loading org-super-links: %S\" err) (kill-emacs 1)))" \
          --eval "(condition-case err (require 'org-super-links-tests) (error (message \"Error loading org-super-links-tests: %S\" err) (kill-emacs 1)))" \
          --eval "(ert-run-tests-batch-and-exit)"